version: 2.1
jobs:
  deploy:
    docker:
      - image: cimg/base:2021.04
    steps:
      - attach_workspace:
          at: ~/
      - add_ssh_keys:
          fingerprints:
            - "$SSH_FINGERPRINT"
      - run:
          name: Check SSH Connection
          command: |
            ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST exit
            if [ $? -eq 0 ]; then
              echo "SSH connection successful"
            else
              echo "SSH connection failed"
              exit 1
            fi
workflows:
  build-and-deploy:
    jobs:
      - deploy
