version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - run:
          command: npm install
          name: npm install
      - run:
          command: npm run build
          name: npm build
      - persist_to_workspace:
          root: ~/
          paths:
            - .

  deploy:
    docker:
      - image: cimg/base:2021.04
    steps:
      - attach_workspace:
          at: ~/
      - add_ssh_keys:
          fingerprints:
            - "$SSH_FINGERPRINT"
      - run:
          name: Test SSH Connection
          command: |
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $SSH_USER@$SSH_HOST ls
      - run:
          name: Upload dist folder
          command: |
            scp dist $SSH_USER@$SSH_HOST:~/demoCI
          when: always  # Continue even if ls or scp fails

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
