version: 2.1
jobs:
  deploy:
    docker:
      - image: cimg/base:2021.04
    steps:
      - attach_workspace:
          at: ~/
      - add_ssh_keys:
          fingerprints:
            - "$SSH_FINGERPRINT"
      - run:
          name: ssh
          command: |
            ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST 'ls'
workflows:
  build-and-deploy:
    jobs:
      - deploy
